language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install: 
  - "npm install -g bower"
install:
  - "bower install"
  - "npm install"
script:
  - "bower install && npm install && node_modules/.bin/enb make"
